function [P_split] = tenseg_spacing(P1,P2,split_num,Spacing_Method)
%% [P_split] = tenseg_spacing(P1,P2,split_num,Spacing_Method) split the
% scalar or vector generated by P1 and P2 by a spacing method and number
% of split points.
% Inputs:
%	P1: point1, it can be a 3x1 vector or a scalar
%   P2: point2, it can be a 3x1 vector or a scalar
%	split_num: number of split points, for example, if n =3, means it will
%              devided into 3 parts.
%   Spacing_Method: Evenly_Spacing, Cosine_Spacing, Equal_Ratio_Spacing,
%                   Natural_Exponential_Spacing, Gaussian_Spacing.
%
% Outputs:
%	P_split: splited ponits stored in this matrix/vector. If input P1 and
%            P2 are scalars, P_split is a vector. If input P1 and P2 are
%            vectors, P_split is a matrix.
%
% Example:
% [P_split] = tenseg_spacing([1 2 3]',[3 2 1]',5,'Evenly_Spacing')
% [P_split] = tenseg_spacing(0,6,6,'Evenly_Spacing')
% [P_split] = tenseg_spacing([0 1 1]',[6 6 1]',6,'Gaussian_Spacing')

%%
P_split = [];
L = -P1 + P2; % spacing from P1 to P2

switch Spacing_Method
    
        % --------------Evening Spacing----------
    case 'Evenly_Spacing'
        % Also called linear spacing.
        for i = 0 : split_num
            P_tem = P1 + L*i/split_num;
            P_split = [P_split P_tem];
        end
        
        % -----------Cosine Spacing--------------
    case 'Cosine_Spacing'
        for i = 0 : split_num
            beta = i*pi/split_num;
            P_tem = P1 + L*(1-cos(beta))/2;
            P_split = [P_split P_tem];
        end
        
        % ----------Equal Ratio Spacing----------
    case 'Equal_Ratio_Spacing'
        % sum{a1 a1*q a1*q^2 ... a1*q^(split_num-1)} = L
        
        % length of sections are increasing if a > 1, length of sections 
        % are evenly if a = 1,  length of sections are decreasig if a < 1.
        
        % Sum of all sections are the length of vector L = -P1 + P2.
        q = 1.2;
        if q == 1 % Equal Ratio Spacing reduced into a evenly spacing method
            a1 = L/split_num;
            for i = 1 : split_num
                P_tem = P1 + i*a1;
                P_split = [P_split P_tem];
            end
            P_split = [P1 P_split];
        else % Equal Ratio Spacing
            a1 = (1-q)/(1-q^split_num)*L;
            for i = 1 : split_num
                P_tem = P1 + (1-q^i)/(1-q)*a1;
                P_split = [P_split P_tem];
            end
            P_split = [P1 P_split];
        end
        
        % -----------Natural exponential Spacing---
    case 'Natural_Exponential_Spacing'
        % length of sections are increasing
        % sum{a1 a1*exp a1*exp^2 ... a1*exp^(split_num-1)} = L
        % Curve is y=a1*exp^(b1*x)
        b1 = 1.1;
        q = exp(1)^b1;
        a1 = (1-q)/(1-q^split_num)*L;
        for i = 1 : split_num
            P_tem = P1 + (1-q^i)/(1-q)*a1;
            P_split = [P_split P_tem];
        end
        P_split = [P1 P_split];
        
        % ----------Gaussian Spacing-------------
    case 'Gaussian_Spacing'
        % Curve is y=1/(sigma*sqrt(2*pi))*exp^(-0.5*((x-mu)/sigma)^2)
        % The cumulative distribution function (CDF) of the normal, or
        % Gaussian, distribution with standard deviation sigma and mean mu
        % is 0.5(1+erf(x-mu)/((sigma*sqrt(2))
        mu = split_num/2; sigma = 1;
        for i = 1 : split_num-1
            P_tem = P1 + 0.5*(1+erf(i-mu)/((sigma*sqrt(2))))*L;
            P_split = [P_split P_tem];
        end
        P_split = [P1 P_split];
        P_split = [P_split P2];
        
        % -----Edit the spacing method database----
    otherwise
        disp('Edit the spacing method database.')
end
end